timezone: America/Argentina/Buenos_Aires

name: Marcas de Hipertexto
description: Ensayo virtual de Augusto Daniele
materia: Diseño Audiovisual, 1ºC 2016, FADU–UBA

baseurl: '/sitio.audiovisual'
url: 'https://tasken.github.io'
permalink: '/ensayo/:title/'

# Sass
sass:
  style: :compressed
  sass_dir: _sass
