name: Ensayo Virtual | Augusto Daniele
description: Ensayo virtual para la materia DAV, FADU-UBA, 2016
google_analytics: null
google_verification: null

baseurl: '/sitio.audiovisual'
url: 'https://tasken.github.io'

# Sass
sass:
  style: :compressed
  sass_dir: _sass
